### ISSUE TITLE
Need a large upgrade on frameworks versions

### ISSUE THREAD

**Issue by ellisonleao** [city41/breakouts#60]
Check out the waffle board for a better view on this effort: https://waffle.io/city41/breakouts

So far 6 engines have been claimed.

**Comment by city41** [comment]
I agree, this is pretty long over due too.

How do you wanna go about it? We could determine which versions need upgrades and make one issue for each one. I'm happy to grab Crafty and Lime for starters.

**Comment by ellisonleao** [comment]
I can get phaser and melonjs for now. Should we create a branch for this?

**Comment by city41** [comment]
Yeah let's do one branch per implementation, then merge them in with PRs.

I'll look into upgrading Crafty this weekend.

**Comment by ellisonleao** [comment]
I am joining Global Game Jam this weekend, so i will probably just start on monday.

**Comment by jerle76** [comment]
I'll contribute to the CreateJS version, unless the original author @solisarg wants to do it.

**Comment by city41** [comment]
thanks @jerle76 

I'll also grab ImpactJS. 

I'll edit the original issue above to keep track of who's got what

**Comment by city41** [comment]
I take that back, this is definitely a good use for Waffle.

Look at the Waffle board for the status on this: https://waffle.io/city41/breakouts

(Waffle uses github issues as its data source)

**Comment by jerle76** [comment]
@city41 can you make me a collaborator of the waffle.io breakouts board so i can claim CreateJS?

**Comment by city41** [comment]
I think it's fair to give @solisarg a chance to step in if he wants. If we don't hear from him I'll happily add you.

**Comment by ellisonleao** [comment]
I can take kiwijs too. I will fill the issue.

**Comment by city41** [comment]
I just finished ImpactJS. I didn't bother with a PR since the upgrade was so easy.

ImpactJS now has sound on mobile devices, nice little bonus of the upgrade.

**Comment by jerle76** [comment]
@city41 fair enough!

**Comment by city41** [comment]
@jerle76 the more I think about it I think you should just go for CreateJS. Breakouts has to be community driven and so it makes sense different people will contribute to implementations.

If @solisarg does want to pitch in, we can work something out.

Thanks a ton for helping!

**Comment by solisarg** [comment]
Hi guys, if @jerle76 wants to work updating createJS version is welcome, lately I'm running out of time with deadlines

**Comment by city41** [comment]
Awesome, thanks solisarg.

**Comment by jerle76** [comment]
thanks @solisarg, I'll get right on it

**Comment by city41** [comment]
I concluded 10 of 12 engines could use upgrades: https://docs.google.com/spreadsheets/d/1PHbn10NqJm4cvzGgPyBS066mDB9-Dc5_D47jb6OaPKs/edit#gid=0

It's difficult to tell if Platypus or FriGame need upgrades. 

@probityrules do you think the Platypus version could use an engine upgrade?

@bugnano do you think the FriGame version could use an engine upgrade?

**Comment by probityrules** [comment]
I think it should be fine for now. The Platypus engine itself has a new version in the works, so once that's ready, I'll update the Platypus breakout game to that release.

**Comment by bugnano** [comment]
I created a pull request with the updated friGame port, but as I have problems with git, can someone just pick the frigame directory from the pull request, please?

**Comment by ellisonleao** [comment]
Hey @bugnano , i will merge your update. Thanks!

**Comment by city41** [comment]
Thanks @bugnano! and thanks @probityrules!
