### ISSUE TITLE
Upgrade Crafty from 0.5.3 to 0.6.3

### ISSUE THREAD

**Issue by city41** [city41/breakouts#62]

**Comment by city41** [comment]
This has been done as of this commit: https://github.com/city41/breakouts/commit/bba9f30ef9e807c82eb93d7b3a039ab611a86d3d

The needed changes are described in the commit message. Mostly just minor tweaks.

Interestingly, the game is very performant on all browsers I tested except desktop Chrome where it's just a tad jerky.

**Comment by ellisonleao** [comment]
:+1:
