### ISSUE TITLE
Upgrade CreateJS

### ISSUE THREAD

**Issue by city41** [city41/breakouts#66]

**Comment by jerle76** [comment]
to CreateJS 2014.12.12 (EaselJS 0.8.0, TweenJS 0.6.0, SoundJS 0.6.0, PreloadJS 0.6.0) from CreateJS 2013.09.25 (EaselJS 0.7.0 (including filters), TweenJS 0.5.0, SoundJS 0.5.0, PreloadJS 0.4.0)

**Comment by city41** [comment]
:+1: 

woot!
