### ISSUE TITLE
melonjs: brick layouts in levels are off

### ISSUE THREAD

**Issue by city41** [city41/breakouts#74]
level 1 has the very first brick on the left is off a tad:

![screen shot 2015-02-28 at 2 07 24 pm](https://cloud.githubusercontent.com/assets/141159/6428146/3872dc52-bf53-11e4-8a49-1e5c65701ad3.png)

and level two is totally wrong:

![screen shot 2015-02-28 at 2 05 24 pm](https://cloud.githubusercontent.com/assets/141159/6428149/425adf30-bf53-11e4-8fe8-b04537d2a9f4.png)

**Comment by obiot** [comment]
I'm confused though, are level 1 and 2 supposed to be the same now ? I just read your other message about the updated design, but did not see anything specifically on the levels

**Comment by city41** [comment]
fixed with https://github.com/city41/breakouts/commit/b2a13d8fb9dcd68126e350a016776e04e4b8ed53

**Comment by city41** [comment]
@obiot we just decided to remove levels 3 and 4. Somehow in the Melon version, level 1 overwrote level 2. I got it fixed now, and I think Melon is good to go.

**Comment by ellisonleao** [comment]
thanks for that fix!
